//TIPOS DE ESTADOS
export const SIDEBAR = "SIDEBAR";
export const SEARCH_MUSIC = "SEARCH_MUSIC";
export const PLAY_MUSIC = "PLAY_MUSIC";
export const VOLUME_OFF_MUSIC = "VOLUME_OFF_MUSIC";
export const MUSIC = "MUSIC";
export const LIST_MUSIC = "LIST_MUSIC";

//TIPOS DE MUTACIONES

export const MUTATION_SIDEBAR = "MUTATION_SIDEBAR";
export const MUTATION_SEARCH_MUSIC = "MUTATION_SEARCH_MUSIC";
export const MUTATION_MUSIC = "MUTATION_MUSIC";
export const MUTATION_PLAY_MUSIC = "MUTATION_PLAY_MUSIC";
export const MUTATION_VOLUME_OFF_MUSIC = "MUTATION_VOLUME_OFF_MUSIC";

export const MUTATION_LIST_MUSIC = "MUTATION_LIST_MUSIC";
